name: flutter_app_riverpod
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^0.12.1
  retrofit: ^1.3.4+1
  freezed_annotation: ^0.12.0
  logging: ^0.11.4
  pretty_dio_logger: ^1.1.1
  webview_flutter: ^0.3.22+1
  state_notifier: ^0.6.0
  flutter_state_notifier: ^0.6.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.7
  freezed: ^0.12.3
  retrofit_generator: ^1.4.0+2
  json_serializable: ^3.5.1

flutter:
  uses-material-design: true